QualityCaps/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QualityCaps.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

QualityCaps/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList;
using QualityCaps.Models;

namespace QualityCaps.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index(string sortOrder, string currentFilter, string searchString,string currentCatagory, int? page)
        {

            var catagoryId = string.IsNullOrWhiteSpace(currentCatagory)
                ? 0
                : Convert.ToInt32(currentCatagory.Substring(0, 1));
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            var catagories = new List<string>();
            foreach (var catagory in db.Catagories)
            {
                catagories.Add(catagory.ID + catagory.Name);
            }
            ViewBag.Catagories = catagories;
            
            if (searchString != null)
            {
                page = 1;
            }
            
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var items = from i in db.Items
                        select i;
            if (catagoryId != 0)
            {
                items = items.Where(s => s.CatagorieId == catagoryId);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper())
                                       || s.Catagorie.Name.ToUpper().Contains(searchString.ToUpper()));
                items = items.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper())
                                       || s.Supplier.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    items = items.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    items = items.OrderByDescending(s => s.Price);
                    break;
                default:  // Name ascending 
                    items = items.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View( items.ToPagedList(pageNumber, pageSize));


            //var items = db.Items.Include(i => i.Catagorie);
            //return View(await items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var colors = new List<string>();
            foreach (var color in db.Colors)
            {
                colors.Add(color.Name);
            }
            ViewBag.Colors = colors;
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name");
            ViewBag.SupplierId = new SelectList(db.Suppliers, "ID", "Name");

            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "ID", "Name", item.SupplierId);
            return View(item);
        }

        // GET: Items/Edit/5
         [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "ID", "Name", item.SupplierId);
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id,Item newItem)
        {
            Item item = await db.Items.FindAsync(id);
            if (id != null)
            {
                item.Name = newItem.Name;
                item.CatagorieId = newItem.CatagorieId;
                item.Price = newItem.Price;
                if (newItem.Image != null)
                {
                    item.Image = newItem.Image;
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            ViewBag.SupplierId = new SelectList(db.Suppliers, "ID", "Name", item.SupplierId);
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Item item = await db.Items.FindAsync(id);
            db.Items.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            Item item = await db.Items.FindAsync(id);

            byte[] photoBack = item.Image;

            return File(photoBack, "image/png");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QualityCaps/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<hgroup>
    <h2>@ViewBag.Title Us</h2>
</hgroup>
<div>
    <div class="col-md-5">
        <address>
            One Microsoft Way<br />
            Redmond, WA 98052-6399<br />
            <abbr title="Phone">P:</abbr>
            425.555.0100
        </address>
        <address>
            <i class="icon-envelope"></i><strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
            <i class="icon-envelope"></i><strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
        </address>
    </div>
    <div class="col-md-7">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12765.708672430546!2d174.7067383!3d-36.880128!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xac4fd7893e9a560f!2sUnitec+Institute+of+Technology!5e0!3m2!1szh-CN!2snz!4v1474113139379" width=100% height="450" frameborder="0" style="border: 0" allowfullscreen></iframe>

    </div>
</div>

QualityCaps/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link href="/Content/banner_jd.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/Scripts/jquery-2.1.1.min.js"></script>
<script src="/Scripts/banner_jd02.js" type="text/javascript"></script>  
<div>
    <h1>Quality Caps</h1>
    <p class="lead">The best cap online shop in New Zealand</p>
    <div class="play_box">
        <div class="imgBox">
            <img alt="" src="/Images/banner1.jpg" />
            <img alt="" src="/Images/banner2.jpg" />
            <img alt="" src="/Images/banner3.jpg" />
            <img alt="" src="/Images/banner4.png" />
        </div>

        <span class="prev" title="Last"></span>
        <span class="next" title="Next"></span>

    </div>
    <p><button type="button" class="btn btn-primary btn-large" onclick="location.href = '@Url.Action("Index", "Items")'">Start Shopping &raquo;</button>
    </p>
</div>