QualityCaps/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog.Fluent;

namespace QualityCaps.Models
{
    public partial class ShoppingCart
    {
        private readonly decimal _gst = new decimal(1.15);
        readonly ApplicationDbContext _storeDb = new ApplicationDbContext();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";

        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public int AddToCart(Item item,string color)
        {
            // Get the matching cart and item instances
            var cartItem = _storeDb.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ItemId == item.ID && c.Color == color);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    ItemId = item.ID,
                    CartId = ShoppingCartId,
                    Color = color,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                _storeDb.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count++;
            }
            // Save changes
            _storeDb.SaveChanges();

            return cartItem.Count;
        }

        public void EmptyCart()
        {
            var cartItems = _storeDb.Carts.Where(
                cart => cart.CartId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                _storeDb.Carts.Remove(cartItem);
            }
            // Save changes
            _storeDb.SaveChanges();
        }

        public List<Cart> GetCartItems()
        {
            return _storeDb.Carts.Where(
                cart => cart.CartId == ShoppingCartId).ToList();
        }

        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in _storeDb.Carts
                          where cartItems.CartId == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }
        public decimal GetSubTotal()
        {
            // Multiply item price by count of that item to get 
            // the current price for each of those items in the cart
            // sum all item price totals to get the cart total
            decimal? total = (from cartItems in _storeDb.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Item.Price).Sum();

            return total ?? decimal.Zero;
        }
        public decimal GetTotal()
        {
            // Multiply item price by count of that item to get 
            // the current price for each of those items in the cart
            // sum all item price totals to get the cart total
            
            decimal? total = (from cartItems in _storeDb.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Item.Price * _gst).Sum();

            return Math.Round(total ?? decimal.Zero , 2);
        }

        public Order CreateOrder(Order order)
        {
            decimal orderTotal = order.Total;
            order.OrderDetails = new List<OrderDetail>();

            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ItemId = item.ItemId,
                    OrderId = order.OrderId,
                    Color = item.Color,
                    UnitPrice = item.Item.Price,
                    Quantity = item.Count,
                    TotalPrice = orderTotal,
                };
                // Set the order total of the shopping cart
                orderTotal += (item.Count * item.Item.Price);
                order.OrderDetails.Add(orderDetail);
                _storeDb.OrderDetails.Add(orderDetail);

            }
            // Set the order's total to the orderTotal count
            order.Total = orderTotal;

            // Save the order
            _storeDb.SaveChanges();
            // Empty the shopping cart
            EmptyCart();
            // Return the OrderId as the confirmation number
            return order;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = _storeDb.Carts.Where(
                c => c.CartId == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.CartId = userName;
            }
            _storeDb.SaveChanges();
        }
    }
}

QualityCaps/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using QualityCaps.Models;

namespace QualityCaps.ViewModels
{
    public class ShoppingCartViewModel
    {
        [Key]
        public List<Cart> CartItems { get; set; }
        public decimal SubTotal { get; set; }
        public decimal CartTotal { get; set; }
    }
}

QualityCaps/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using QualityCaps.Models;
using QualityCaps.ViewModels;

namespace QualityCaps.Controllers
{
    public class ShoppingCartController : Controller
    {
        readonly ApplicationDbContext _storeDb = new ApplicationDbContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                SubTotal = cart.GetSubTotal(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }

        //
        // POST: /Store/RemoveAllItems/5

        public ActionResult RemoveAllItems()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.EmptyCart();
            return RedirectToAction("Index");
        }

        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id,string color)
        {
            // Retrieve the item from the database
            var addedItem = _storeDb.Items
                .Single(item => item.ID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            if (string.IsNullOrWhiteSpace(color))
                color = "UnSelected";
            int count = cart.AddToCart(addedItem,color);
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(addedItem.Name) +
                    " has been added to your shopping cart.",
                CartTotal = cart.GetTotal(),
                SubTotal = cart.GetSubTotal(),
                CartCount = cart.GetCount(),
                ItemCount = count,
                DeleteId = id
            };
            return Json(results);

            // Go back to the main store page for more shopping
           // return RedirectToAction("Index");
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

QualityCaps/Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Cart</strong>  <span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

QualityCaps/Views/ShoppingCart/Index.cshtml
@model QualityCaps.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<script src="../../Scripts/jquery-2.1.1.min.js"></script>

<h3>
    <em>Review</em> your cart:
</h3>
<br/>
<div class="top-right">
    <a style="text-align: right">@Html.ActionLink("Clear Cart", "RemoveAllItems")</a>
</div>
<br />

@{

    if (Model.CartItems.Count > 0) 
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Item ID
                            </th>
                            <th>
                                Item Name
                            </th>
                            <th>
                                Catagory
                            </th>
                            <th>
                                Supplier
                            </th>
                            <th>
                                Color
                            </th>
                            <th>
                                Price (each)
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ItemId" >
                            <td>
                                @item.Item.ID
                            </td>
                            <td>
                                @item.Item.Name
                            </td>
                            <td>
                                @item.Item.Catagorie.Name
                            </td>
                            <td>
                                @item.Item.Supplier.Name
                            </td>
                            <td>
                                @item.Color
                            </td>
                            <td>
                                @item.Item.Price
                            </td>
                            <td id="item-count-@item.ItemId">
                                @item.Count
                            </td>

                        </tr>
                    }
                    <tr class="info">
                        <td>
                            SubTotal
                        </td>
                        <td id="subtotal">
                            @Model.SubTotal
                        </td>
                        <td>
                            Total(GST:15%)
                        </td>
                        <td id="cart-total">
                            @Model.CartTotal
                        </td>
                    </tr>
                </table>
                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("AddressAndPayment", "Checkout")'">
                    Check Out &raquo;
                </button>
            </div>
        </div>
    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}